"""
Deterministic Multiresolution Volume Generator & Brick Extractor (TASK-04B).

Extracts and builds multiresolution 3D volume pyramids and sub-volume bricks from canonical
Zarr stores for WebGPU / WebGL2 scientific ocean volume rendering according to approved
TASK-04A specifications:
- Brick Shape: (64, 64, 32) [lon, lat, depth]
- Boundary Halo: (1, 1, 0) [lon, lat, depth] -> Allocated Shape (66, 66, 32)
- Hierarchy: Strategy 3 (Horizontal 2x2 downsampling, vertical 31 levels preserved with 1D Depth LUT)
  - LOD 0: (97, 181, 31) -> (2, 3, 1) = 6 bricks / timestep
  - LOD 1: (49, 91, 31) -> (1, 2, 1) = 2 bricks / timestep
  - LOD 2: (25, 46, 31) -> (1, 1, 1) = 1 brick / timestep
- Precision: Float16 primary ('r16float') + Linear Uint16 fallback with reserved missing code 65535.
- Downsampling rule: Mask-preserving arithmetic mean of valid sub-voxels.
- Determinism: Bitwise reproducible outputs, deterministic manifests, SHA-256 integrity verification.
"""

from __future__ import annotations

import hashlib
import json
import logging
import math
import os
import shutil
import tempfile
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

import numcodecs
import numpy as np
import zarr

from quasar_contracts.horizontal_grids import SpatialBoundingBox
from quasar_contracts.visualization_contracts import (
    AggregationMethod,
    BackendCompatibility,
    BrickGeometryContract,
    BrickIdentityContract,
    BrickPayloadContract,
    CompressionCodec,
    CoordinateSpace,
    CoordinateTransformContract,
    MultiresolutionLevelContract,
    OutOfRangeRenderingPolicy,
    QuantizationContract,
    RenderStatisticsContract,
    TextureSampleFormat,
    TransferFunctionContract,
    TransferFunctionControlPoint,
    VisualizationProductContract,
)

logger = logging.getLogger(__name__)


@dataclass
class BrickExtractionResult:
    """Metadata and raw/compressed binary properties for an individual extracted brick."""
    identity: BrickIdentityContract
    geometry: BrickGeometryContract
    payload_f16: BrickPayloadContract
    payload_u16: BrickPayloadContract
    f16_bytes: bytes
    u16_bytes: bytes
    f16_zstd_bytes: bytes
    u16_zstd_bytes: bytes


@dataclass
class MultiresolutionPyramidResult:
    """Summary and artifacts generated by the multiresolution generator."""
    visualization_product_id: str
    product_version: str
    source_snapshot_id: str
    variable_id: str
    staging_directory: Path
    timesteps_count: int
    lod_levels_count: int
    total_bricks_count: int
    depth_lut_m: List[float]
    global_scalar_range: Tuple[float, float]
    quantization_contract: QuantizationContract
    brick_manifest: List[Dict[str, Any]]
    visualization_manifest: Dict[str, Any]
    manifest_sha256: str


class MultiresolutionGenerator:
    """
    Authoritative multiresolution brick generator adhering strictly to TASK-04A specifications.
    """

    BRICK_SHAPE = (64, 64, 32)  # [nx, ny, nz] (lon, lat, depth)
    HALO_PADDING = (1, 1, 0)     # [hx, hy, hz]
    ALLOCATED_SHAPE = (66, 66, 32)  # [64+2*1, 64+2*1, 32+2*0]
    RESERVED_MISSING_U16 = 65535
    ZSTD_COMPRESSION_LEVEL = 3

    def __init__(
        self,
        canonical_zarr_path: Union[str, Path],
        variable_id: str = "sea_water_potential_temperature",
        mask_id: str = "validity_mask",
        visualization_product_id: Optional[str] = None,
        product_version: str = "v1",
    ):
        self.canonical_zarr_path = Path(canonical_zarr_path).resolve()
        if not self.canonical_zarr_path.exists():
            raise FileNotFoundError(f"Canonical Zarr store not found at {self.canonical_zarr_path}")

        self.variable_id = variable_id
        self.mask_id = mask_id
        self.product_version = product_version

        # Load store and arrays
        self.store = zarr.open(str(self.canonical_zarr_path), mode="r")
        if self.variable_id not in self.store:
            raise KeyError(f"Variable '{self.variable_id}' not found in canonical store.")
        if self.mask_id not in self.store:
            raise KeyError(f"Mask '{self.mask_id}' not found in canonical store.")

        self.data_arr = self.store[self.variable_id]
        self.mask_arr = self.store[self.mask_id]
        self.depth_arr = self.store["depth"][:] if "depth" in self.store else None
        self.lat_arr = self.store["latitude"][:] if "latitude" in self.store else None
        self.lon_arr = self.store["longitude"][:] if "longitude" in self.store else None
        self.time_arr = self.store["time"][:] if "time" in self.store else None

        if self.depth_arr is None or self.lat_arr is None or self.lon_arr is None:
            raise ValueError("Canonical store must contain 'depth', 'latitude', and 'longitude' coordinates.")

        self.num_time, self.nz, self.ny, self.nx = self.data_arr.shape
        if self.nz != 31 or self.ny != 181 or self.nx != 97:
            logger.warning(
                f"Dataset shape {(self.num_time, self.nz, self.ny, self.nx)} differs from standard Copernicus baseline (7, 31, 181, 97)"
            )

        self.snapshot_id = self.canonical_zarr_path.name
        self.visualization_product_id = (
            visualization_product_id or f"vis_{self.snapshot_id}_{self.variable_id}"
        )

        self.zstd_codec = numcodecs.Zstd(level=self.ZSTD_COMPRESSION_LEVEL)

    @staticmethod
    def downsample_horizontal_2x(
        data: np.ndarray, mask: np.ndarray
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Downsamples a 3D volume (depth, lat, lon) horizontally by 2x using
        the approved mask-preserving arithmetic mean of valid sub-voxels.
        
        A coarse cell is VALID (0) if and only if >= 1 sub-voxel is valid (mask == 0).
        If all sub-voxels are non-valid, the coarse cell is SOURCE_MISSING (1).
        """
        nz, ny, nx = data.shape
        out_ny = int(math.ceil(ny / 2.0))
        out_nx = int(math.ceil(nx / 2.0))

        out_data = np.full((nz, out_ny, out_nx), np.nan, dtype=np.float32)
        out_mask = np.full((nz, out_ny, out_nx), 1, dtype=np.uint8)

        for iz in range(nz):
            for iy in range(out_ny):
                y0 = iy * 2
                y1 = min(y0 + 2, ny)
                for ix in range(out_nx):
                    x0 = ix * 2
                    x1 = min(x0 + 2, nx)

                    sub_data = data[iz, y0:y1, x0:x1]
                    sub_mask = mask[iz, y0:y1, x0:x1]

                    valid_pts = sub_data[sub_mask == 0]
                    if len(valid_pts) > 0:
                        out_data[iz, iy, ix] = np.mean(valid_pts)
                        out_mask[iz, iy, ix] = 0
                    else:
                        # Determine dominant invalid reason (LAND vs SOURCE_MISSING)
                        # If any sub-voxel is LAND (2), mark as LAND (2), else SOURCE_MISSING (1)
                        if np.any(sub_mask == 2):
                            out_mask[iz, iy, ix] = 2
                        else:
                            out_mask[iz, iy, ix] = 1

        return out_data, out_mask

    def compute_lod_pyramid_for_timestep(
        self, timestep_idx: int
    ) -> List[Tuple[int, np.ndarray, np.ndarray]]:
        """
        Generates LOD 0, LOD 1, and LOD 2 volumes for a given timestep.
        Returns list of (lod_level, data_float32, mask_uint8).
        """
        t_data = self.data_arr[timestep_idx][:].astype(np.float32)
        t_mask = self.mask_arr[timestep_idx][:].astype(np.uint8)

        # LOD 0: Native (nz=31, ny=181, nx=97)
        lod0_data = t_data
        lod0_mask = t_mask

        # LOD 1: 2x2 horizontal downsampling (nz=31, ny=91, nx=49)
        lod1_data, lod1_mask = self.downsample_horizontal_2x(lod0_data, lod0_mask)

        # LOD 2: 4x4 horizontal downsampling (downsample LOD 1 by 2x) (nz=31, ny=46, nx=25)
        lod2_data, lod2_mask = self.downsample_horizontal_2x(lod1_data, lod1_mask)

        return [
            (0, lod0_data, lod0_mask),
            (1, lod1_data, lod1_mask),
            (2, lod2_data, lod2_mask),
        ]

    def compute_global_quantization_parameters(self) -> Tuple[float, float, QuantizationContract]:
        """
        Computes deterministic global affine quantization parameters across all valid oceanic samples.
        """
        # Read full volume to determine global scalar bounds
        all_mask = self.mask_arr[:]
        valid_indices = all_mask == 0
        all_data = self.data_arr[:]
        valid_samples = all_data[valid_indices]

        if len(valid_samples) == 0:
            raise ValueError("No valid samples found in canonical dataset!")

        min_val = float(np.min(valid_samples))
        max_val = float(np.max(valid_samples))

        if max_val == min_val:
            scale_factor = 1.0 / 65534.0
        else:
            scale_factor = (max_val - min_val) / 65534.0
        add_offset = min_val

        quant_contract = QuantizationContract(
            scale_factor=scale_factor,
            add_offset=add_offset,
            quantized_data_type="uint16",
            unquantized_data_type="float32",
            reserved_missing_code=self.RESERVED_MISSING_U16,
            theoretical_max_quantization_error=0.5 * scale_factor,
            is_eligible_for_exact_query=False,
        )

        return min_val, max_val, quant_contract

    def extract_brick(
        self,
        lod_level: int,
        timestep_idx: int,
        bx_idx: int,
        by_idx: int,
        bz_idx: int,
        volume_data: np.ndarray,  # (nz, ny, nx)
        volume_mask: np.ndarray,  # (nz, ny, nx)
        scale_factor: float,
        add_offset: float,
    ) -> BrickExtractionResult:
        """
        Extracts a single sub-volume brick with 1-voxel horizontal halo ([1, 1, 0]),
        generating Float16 and Uint16 binary payloads and validation metadata.
        """
        nz, ny, nx = volume_data.shape
        bx_size, by_size, bz_size = self.BRICK_SHAPE
        halo_x, halo_y, halo_z = self.HALO_PADDING
        alloc_x, alloc_y, alloc_z = self.ALLOCATED_SHAPE

        # Interior voxel bounds in volume sample coordinates
        x0 = bx_idx * bx_size
        x1 = min(x0 + bx_size, nx)
        y0 = by_idx * by_size
        y1 = min(y0 + by_size, ny)
        z0 = bz_idx * bz_size
        z1 = min(z0 + bz_size, nz)

        interior_shape = [x1 - x0, y1 - y0, z1 - z0]

        # Halo extended bounds in volume sample coordinates
        hx0 = max(0, x0 - halo_x)
        hx1 = min(nx, x1 + halo_x)
        hy0 = max(0, y0 - halo_y)
        hy1 = min(ny, y1 + halo_y)
        hz0 = max(0, z0 - halo_z)
        hz1 = min(nz, z1 + halo_z)

        # Slice sub-volume with halo
        sub_data = volume_data[hz0:hz1, hy0:hy1, hx0:hx1]
        sub_mask = volume_mask[hz0:hz1, hy0:hy1, hx0:hx1]

        # Allocated brick buffers in column-major / standard memory layout: shape (alloc_z, alloc_y, alloc_x)
        arr_f16 = np.full((alloc_z, alloc_y, alloc_x), np.nan, dtype=np.float16)
        arr_u16 = np.full((alloc_z, alloc_y, alloc_x), self.RESERVED_MISSING_U16, dtype=np.uint16)

        # Calculate insertion offsets into allocated brick buffer
        off_x = halo_x - (x0 - hx0)
        off_y = halo_y - (y0 - hy0)
        off_z = halo_z - (z0 - hz0)

        act_z, act_y, act_x = sub_data.shape

        # Fill Float16 buffer (NaN for missing/land samples)
        sub_valid = sub_mask == 0
        sub_f16_values = np.where(sub_valid, sub_data.astype(np.float16), np.nan)
        arr_f16[off_z : off_z + act_z, off_y : off_y + act_y, off_x : off_x + act_x] = sub_f16_values

        # Fill Uint16 buffer (affine quantized for valid samples, 65535 for missing)
        quant_sub = np.where(
            sub_valid,
            np.round((sub_data - add_offset) / scale_factor).clip(0, 65534),
            self.RESERVED_MISSING_U16,
        ).astype(np.uint16)
        arr_u16[off_z : off_z + act_z, off_y : off_y + act_y, off_x : off_x + act_x] = quant_sub

        # Compute valid statistics within the INTERIOR of the brick
        interior_sub_data = volume_data[z0:z1, y0:y1, x0:x1]
        interior_sub_mask = volume_mask[z0:z1, y0:y1, x0:x1]
        interior_valid = interior_sub_data[interior_sub_mask == 0]

        is_empty_or_masked = len(interior_valid) == 0
        min_val = float(np.min(interior_valid)) if len(interior_valid) > 0 else None
        max_val = float(np.max(interior_valid)) if len(interior_valid) > 0 else None

        # Determine spatial geographic bounds (from native lon/lat arrays)
        # Compute effective lon/lat coordinates for this LOD
        min_lon = float(self.lon_arr[min(x0, nx - 1)])
        max_lon = float(self.lon_arr[min(max(x1 - 1, x0), nx - 1)])
        min_lat = float(self.lat_arr[min(y0, ny - 1)])
        max_lat = float(self.lat_arr[min(max(y1 - 1, y0), ny - 1)])

        min_depth = float(self.depth_arr[min(z0, nz - 1)])
        max_depth = float(self.depth_arr[min(max(z1 - 1, z0), nz - 1)])

        # Construct identity
        identity = BrickIdentityContract(
            visualization_product_id=self.visualization_product_id,
            product_version=self.product_version,
            lod_level=lod_level,
            timestep_index=timestep_idx,
            brick_index_x=bx_idx,
            brick_index_y=by_idx,
            brick_index_z=bz_idx,
            variable_id=self.variable_id,
        )
        brick_key = identity.composite_key

        # Raw byte buffers
        f16_bytes = arr_f16.tobytes()
        u16_bytes = arr_u16.tobytes()
        f16_raw_sha256 = hashlib.sha256(f16_bytes).hexdigest()

        # Compressed buffers
        f16_zstd = self.zstd_codec.encode(f16_bytes)
        u16_zstd = self.zstd_codec.encode(u16_bytes)
        f16_cmp_sha256 = hashlib.sha256(f16_zstd).hexdigest()
        u16_cmp_sha256 = hashlib.sha256(u16_zstd).hexdigest()

        # Geometry contract
        geometry = BrickGeometryContract(
            brick_key=brick_key,
            sample_origin=[x0, y0, z0],
            sample_shape=[alloc_x, alloc_y, alloc_z],
            interior_valid_shape=interior_shape,
            halo_padding=[halo_x, halo_y, halo_z],
            spatial_bounds=SpatialBoundingBox(
                min_longitude=min_lon,
                min_latitude=min_lat,
                max_longitude=max_lon,
                max_latitude=max_lat,
            ),
            min_depth_m=min_depth,
            max_depth_m=max_depth,
            min_value=min_val,
            max_value=max_val,
            is_empty_or_masked=is_empty_or_masked,
            payload_sha256=f16_raw_sha256,
        )

        # Storage keys (relative)
        f16_storage_key = f"lod{lod_level}/t{timestep_idx}/b_{bx_idx}_{by_idx}_{bz_idx}_f16.bin.zst"
        u16_storage_key = f"lod{lod_level}/t{timestep_idx}/b_{bx_idx}_{by_idx}_{bz_idx}_u16.bin.zst"

        payload_f16 = BrickPayloadContract(
            brick_key=brick_key,
            storage_object_key=f16_storage_key,
            compression_codec=CompressionCodec.ZSTD,
            sample_format=TextureSampleFormat.R16_FLOAT,
            uncompressed_bytes_length=len(f16_bytes),
            compressed_bytes_length=len(f16_zstd),
            sha256_checksum=f16_cmp_sha256,
            quantization=None,
        )

        payload_u16 = BrickPayloadContract(
            brick_key=brick_key,
            storage_object_key=u16_storage_key,
            compression_codec=CompressionCodec.ZSTD,
            sample_format=TextureSampleFormat.R16_UINT,
            uncompressed_bytes_length=len(u16_bytes),
            compressed_bytes_length=len(u16_zstd),
            sha256_checksum=u16_cmp_sha256,
            quantization=QuantizationContract(
                scale_factor=scale_factor,
                add_offset=add_offset,
                quantized_data_type="uint16",
                unquantized_data_type="float32",
                reserved_missing_code=self.RESERVED_MISSING_U16,
                theoretical_max_quantization_error=0.5 * scale_factor,
                is_eligible_for_exact_query=False,
            ),
        )

        return BrickExtractionResult(
            identity=identity,
            geometry=geometry,
            payload_f16=payload_f16,
            payload_u16=payload_u16,
            f16_bytes=f16_bytes,
            u16_bytes=u16_bytes,
            f16_zstd_bytes=f16_zstd,
            u16_zstd_bytes=u16_zstd,
        )

    def generate_all(
        self,
        output_staging_dir: Union[str, Path],
    ) -> MultiresolutionPyramidResult:
        """
        Executes complete deterministic multiresolution volume generation across all timesteps and LODs.
        Writes binary assets and manifests directly into the output staging directory.
        """
        staging_dir = Path(output_staging_dir).resolve()
        staging_dir.mkdir(parents=True, exist_ok=True)

        logger.info(f"Starting multiresolution generation into {staging_dir}")

        min_val, max_val, quant_contract = self.compute_global_quantization_parameters()

        depth_lut_m = [float(z) for z in self.depth_arr]

        # Calculate render statistics across all valid samples
        all_mask = self.mask_arr[:]
        all_data = self.data_arr[:]
        valid_samples = all_data[all_mask == 0]

        p01 = float(np.percentile(valid_samples, 1.0))
        p50 = float(np.percentile(valid_samples, 50.0))
        p99 = float(np.percentile(valid_samples, 99.0))
        mean_val = float(np.mean(valid_samples))
        std_val = float(np.std(valid_samples))
        missing_frac = float(np.sum(all_mask != 0) / all_mask.size)

        hist_counts, bin_edges = np.histogram(valid_samples, bins=64)

        render_stats = RenderStatisticsContract(
            valid_min=min_val,
            valid_max=max_val,
            percentile_01=p01,
            percentile_50=p50,
            percentile_99=p99,
            mean_value=mean_val,
            std_dev_value=std_val,
            histogram_bin_edges=[float(e) for e in bin_edges],
            histogram_counts=[int(c) for c in hist_counts],
            missing_sample_fraction=missing_frac,
        )

        # Coordinate Transform Contract
        origin_lon = float(np.mean([self.lon_arr[0], self.lon_arr[-1]]))
        origin_lat = float(np.mean([self.lat_arr[0], self.lat_arr[-1]]))

        coord_transform = CoordinateTransformContract(
            source_coordinate_space=CoordinateSpace.GEOGRAPHIC_WGS84,
            target_coordinate_space=CoordinateSpace.DISPLAY_VOLUME_LAB,
            origin_longitude_deg=origin_lon,
            origin_latitude_deg=origin_lat,
            origin_depth_m=float(self.depth_arr[0]),
            scale_x_meters=1.0,
            scale_y_meters=1.0,
            scale_z_meters=1.0,
            vertical_exaggeration_factor=100.0,
            uses_non_uniform_depth_lut=True,
            depth_lut_entries_m=depth_lut_m,
        )

        # Transfer function default (cmocean_thermal / thermal colormap)
        default_tf = TransferFunctionContract(
            colormap_preset_name="cmocean_thermal",
            physical_domain_min=min_val,
            physical_domain_max=max_val,
            physical_units="degree_Celsius",
            control_points=[
                TransferFunctionControlPoint(normalized_position=0.0, red=0.05, green=0.10, blue=0.45, opacity=0.0),
                TransferFunctionControlPoint(normalized_position=0.25, red=0.15, green=0.40, blue=0.75, opacity=0.15),
                TransferFunctionControlPoint(normalized_position=0.50, red=0.90, green=0.70, blue=0.20, opacity=0.40),
                TransferFunctionControlPoint(normalized_position=0.75, red=0.95, green=0.40, blue=0.10, opacity=0.70),
                TransferFunctionControlPoint(normalized_position=1.0, red=0.85, green=0.10, blue=0.10, opacity=0.95),
            ],
            out_of_range_policy=OutOfRangeRenderingPolicy.DISCARD_TRANSPARENT,
            missing_value_color_rgba=[0.0, 0.0, 0.0, 0.0],
        )

        all_brick_manifests: List[Dict[str, Any]] = []
        total_brick_count = 0
        lod_levels_contracts: List[MultiresolutionLevelContract] = []

        # Iterate over timesteps
        for t_idx in range(self.num_time):
            lod_pyramids = self.compute_lod_pyramid_for_timestep(t_idx)

            for lod_lvl, vol_data, vol_mask in lod_pyramids:
                cur_nz, cur_ny, cur_nx = vol_data.shape
                bx_size, by_size, bz_size = self.BRICK_SHAPE

                nx_bricks = int(math.ceil(cur_nx / bx_size))
                ny_bricks = int(math.ceil(cur_ny / by_size))
                nz_bricks = int(math.ceil(cur_nz / bz_size))

                # If first timestep, record LOD level contract
                if t_idx == 0:
                    ds_factor = 2 ** lod_lvl
                    dx_deg = float(np.abs(np.mean(np.diff(self.lon_arr)))) * ds_factor
                    dy_deg = float(np.abs(np.mean(np.diff(self.lat_arr)))) * ds_factor

                    lod_contract = MultiresolutionLevelContract(
                        lod_level=lod_lvl,
                        grid_shape=[cur_nx, cur_ny, cur_nz],
                        brick_shape=list(self.BRICK_SHAPE),
                        brick_grid_shape=[nx_bricks, ny_bricks, nz_bricks],
                        total_brick_count=nx_bricks * ny_bricks * nz_bricks,
                        aggregation_method=AggregationMethod.AVERAGE_2X2X2,
                        sample_data_type="float16",
                        voxel_resolution_x_deg=dx_deg,
                        voxel_resolution_y_deg=dy_deg,
                    )
                    lod_levels_contracts.append(lod_contract)

                # Ensure output subdirectories exist
                lod_t_dir = staging_dir / f"lod{lod_lvl}" / f"t{t_idx}"
                lod_t_dir.mkdir(parents=True, exist_ok=True)

                for iz in range(nz_bricks):
                    for iy in range(ny_bricks):
                        for ix in range(nx_bricks):
                            brick_res = self.extract_brick(
                                lod_level=lod_lvl,
                                timestep_idx=t_idx,
                                bx_idx=ix,
                                by_idx=iy,
                                bz_idx=iz,
                                volume_data=vol_data,
                                volume_mask=vol_mask,
                                scale_factor=quant_contract.scale_factor,
                                add_offset=quant_contract.add_offset,
                            )

                            # Save Float16 compressed brick
                            f16_file = staging_dir / brick_res.payload_f16.storage_object_key
                            with open(f16_file, "wb") as f:
                                f.write(brick_res.f16_zstd_bytes)

                            # Save Uint16 compressed brick
                            u16_file = staging_dir / brick_res.payload_u16.storage_object_key
                            with open(u16_file, "wb") as f:
                                f.write(brick_res.u16_zstd_bytes)

                            brick_entry = {
                                "brick_key": brick_res.identity.composite_key,
                                "identity": brick_res.identity.model_dump(),
                                "geometry": brick_res.geometry.model_dump(),
                                "payload_f16": brick_res.payload_f16.model_dump(),
                                "payload_u16": brick_res.payload_u16.model_dump(),
                            }
                            all_brick_manifests.append(brick_entry)
                            total_brick_count += 1

        # Sort brick manifests deterministically by composite key
        all_brick_manifests.sort(key=lambda b: b["brick_key"])

        # Spatial bounding box
        global_bounds = SpatialBoundingBox(
            min_longitude=float(self.lon_arr[0]),
            min_latitude=float(self.lat_arr[0]),
            max_longitude=float(self.lon_arr[-1]),
            max_latitude=float(self.lat_arr[-1]),
        )

        vis_product = VisualizationProductContract(
            visualization_product_id=self.visualization_product_id,
            product_version=self.product_version,
            source_dataset_id=self.snapshot_id,
            source_variable_id=self.variable_id,
            canonical_units="degree_Celsius",
            source_asset_ids=[self.snapshot_id],
            source_asset_checksums={self.snapshot_id: "deterministic_canonical"},
            processing_pipeline_version="1.0.0",
            backend_compatibility=BackendCompatibility.BOTH_SUPPORTED,
            spatial_bounds=global_bounds,
            min_depth_m=float(self.depth_arr[0]),
            max_depth_m=float(self.depth_arr[-1]),
            timestep_count=self.num_time,
            available_lod_levels=lod_levels_contracts,
            coordinate_transform=coord_transform,
            render_statistics=render_stats,
            default_transfer_function=default_tf,
            brick_template_url="lod{lod}/t{time}/b_{bx}_{by}_{bz}_f16.bin.zst",
        )

        # Write out manifests
        manifest_data = {
            "schema_version": "1.0.0",
            "task_id": "TASK-04B",
            "visualization_product": vis_product.model_dump(),
            "quantization_contract": quant_contract.model_dump(),
            "total_bricks": total_brick_count,
            "bricks": all_brick_manifests,
        }

        manifest_json_bytes = json.dumps(manifest_data, indent=2, sort_keys=True).encode("utf-8")
        manifest_sha256 = hashlib.sha256(manifest_json_bytes).hexdigest()

        manifest_path = staging_dir / "visualization_manifest.json"
        with open(manifest_path, "wb") as f:
            f.write(manifest_json_bytes)

        # Write separate lightweight brick catalog index
        brick_catalog_path = staging_dir / "brick_catalog.json"
        with open(brick_catalog_path, "w", encoding="utf-8") as f:
            json.dump(
                {
                    "visualization_product_id": self.visualization_product_id,
                    "total_bricks": total_brick_count,
                    "manifest_sha256": manifest_sha256,
                    "bricks": all_brick_manifests,
                },
                f,
                indent=2,
                sort_keys=True,
            )

        logger.info(
            f"Multiresolution generation complete: {total_brick_count} bricks written to {staging_dir}"
        )

        return MultiresolutionPyramidResult(
            visualization_product_id=self.visualization_product_id,
            product_version=self.product_version,
            source_snapshot_id=self.snapshot_id,
            variable_id=self.variable_id,
            staging_directory=staging_dir,
            timesteps_count=self.num_time,
            lod_levels_count=len(lod_levels_contracts),
            total_bricks_count=total_brick_count,
            depth_lut_m=depth_lut_m,
            global_scalar_range=(min_val, max_val),
            quantization_contract=quant_contract,
            brick_manifest=all_brick_manifests,
            visualization_manifest=manifest_data,
            manifest_sha256=manifest_sha256,
        )
